let array = {
  Headline: {
    EffectiveDate: '2019-12-21T07:00:00+06:00',
    EffectiveEpochDate: 1576890000,
    Severity: 7,
    Text: 'Partly sunny this weekend',
    Category: '',
    EndDate: null,
    EndEpochDate: null,
    MobileLink:
      'http://m.accuweather.com/en/bd/dhaka/28143/extended-weather-forecast/28143?unit=c&lang=en-us',
    Link:
      'http://www.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?unit=c&lang=en-us',
  },
  DailyForecasts: [
    {
      Date: '2019-12-16T07:00:00+06:00',
      EpochDate: 1576458000,
      Sun: {
        Rise: '2019-12-16T06:33:00+06:00',
        EpochRise: 1576456380,
        Set: '2019-12-16T17:14:00+06:00',
        EpochSet: 1576494840,
      },
      Moon: {
        Rise: '2019-12-16T21:24:00+06:00',
        EpochRise: 1576509840,
        Set: '2019-12-17T10:53:00+06:00',
        EpochSet: 1576558380,
        Phase: 'WaningGibbous',
        Age: 20,
      },
      Temperature: {
        Minimum: {Value: 16.2, Unit: 'C', UnitType: 17},
        Maximum: {Value: 26.3, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperature: {
        Minimum: {Value: 16.3, Unit: 'C', UnitType: 17},
        Maximum: {Value: 27.2, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperatureShade: {
        Minimum: {Value: 16.3, Unit: 'C', UnitType: 17},
        Maximum: {Value: 25.7, Unit: 'C', UnitType: 17},
      },
      HoursOfSun: 4.6,
      DegreeDaySummary: {
        Heating: {Value: 0.0, Unit: 'C', UnitType: 17},
        Cooling: {Value: 3.0, Unit: 'C', UnitType: 17},
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Particle Pollution',
        },
        {Name: 'Grass', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Mold', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Ragweed', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Tree', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'UVIndex', Value: 2, Category: 'Low', CategoryValue: 1},
      ],
      Day: {
        Icon: 4,
        IconPhrase: 'Intermittent clouds',
        HasPrecipitation: false,
        ShortPhrase: 'Pleasant with clouds and sun',
        LongPhrase: 'Delightful with intervals of clouds and sunshine',
        PrecipitationProbability: 11,
        ThunderstormProbability: 0,
        RainProbability: 11,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 5.6, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 340, Localized: 'NNW', English: 'NNW'},
        },
        WindGust: {
          Speed: {Value: 18.5, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 336, Localized: 'NNW', English: 'NNW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 51,
      },
      Night: {
        Icon: 33,
        IconPhrase: 'Clear',
        HasPrecipitation: false,
        ShortPhrase: 'Clear',
        LongPhrase: 'Clear',
        PrecipitationProbability: 2,
        ThunderstormProbability: 0,
        RainProbability: 2,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 7.4, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 327, Localized: 'NNW', English: 'NNW'},
        },
        WindGust: {
          Speed: {Value: 11.1, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 333, Localized: 'NNW', English: 'NNW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 8,
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://m.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=1&unit=c&lang=en-us',
      Link:
        'http://www.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=1&unit=c&lang=en-us',
    },
    {
      Date: '2019-12-17T07:00:00+06:00',
      EpochDate: 1576544400,
      Sun: {
        Rise: '2019-12-17T06:34:00+06:00',
        EpochRise: 1576542840,
        Set: '2019-12-17T17:15:00+06:00',
        EpochSet: 1576581300,
      },
      Moon: {
        Rise: '2019-12-17T22:26:00+06:00',
        EpochRise: 1576599960,
        Set: '2019-12-18T11:37:00+06:00',
        EpochSet: 1576647420,
        Phase: 'WaningGibbous',
        Age: 21,
      },
      Temperature: {
        Minimum: {Value: 14.1, Unit: 'C', UnitType: 17},
        Maximum: {Value: 26.1, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperature: {
        Minimum: {Value: 13.4, Unit: 'C', UnitType: 17},
        Maximum: {Value: 26.8, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperatureShade: {
        Minimum: {Value: 13.4, Unit: 'C', UnitType: 17},
        Maximum: {Value: 24.8, Unit: 'C', UnitType: 17},
      },
      HoursOfSun: 9.1,
      DegreeDaySummary: {
        Heating: {Value: 0.0, Unit: 'C', UnitType: 17},
        Cooling: {Value: 2.0, Unit: 'C', UnitType: 17},
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {Name: 'Grass', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Mold', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Ragweed', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Tree', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'UVIndex', Value: 4, Category: 'Moderate', CategoryValue: 2},
      ],
      Day: {
        Icon: 2,
        IconPhrase: 'Mostly sunny',
        HasPrecipitation: false,
        ShortPhrase: 'Mostly sunny and delightful',
        LongPhrase: 'Mostly sunny and delightful',
        PrecipitationProbability: 1,
        ThunderstormProbability: 0,
        RainProbability: 1,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 9.3, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 321, Localized: 'NW', English: 'NW'},
        },
        WindGust: {
          Speed: {Value: 13.0, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 295, Localized: 'WNW', English: 'WNW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 15,
      },
      Night: {
        Icon: 33,
        IconPhrase: 'Clear',
        HasPrecipitation: false,
        ShortPhrase: 'Clear',
        LongPhrase: 'Clear',
        PrecipitationProbability: 0,
        ThunderstormProbability: 0,
        RainProbability: 0,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 7.4, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 338, Localized: 'NNW', English: 'NNW'},
        },
        WindGust: {
          Speed: {Value: 13.0, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 325, Localized: 'NW', English: 'NW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 1,
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://m.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=2&unit=c&lang=en-us',
      Link:
        'http://www.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=2&unit=c&lang=en-us',
    },
    {
      Date: '2019-12-18T07:00:00+06:00',
      EpochDate: 1576630800,
      Sun: {
        Rise: '2019-12-18T06:34:00+06:00',
        EpochRise: 1576629240,
        Set: '2019-12-18T17:15:00+06:00',
        EpochSet: 1576667700,
      },
      Moon: {
        Rise: '2019-12-18T23:28:00+06:00',
        EpochRise: 1576690080,
        Set: '2019-12-19T12:17:00+06:00',
        EpochSet: 1576736220,
        Phase: 'WaningGibbous',
        Age: 22,
      },
      Temperature: {
        Minimum: {Value: 12.9, Unit: 'C', UnitType: 17},
        Maximum: {Value: 25.5, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperature: {
        Minimum: {Value: 12.5, Unit: 'C', UnitType: 17},
        Maximum: {Value: 26.6, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperatureShade: {
        Minimum: {Value: 12.5, Unit: 'C', UnitType: 17},
        Maximum: {Value: 24.2, Unit: 'C', UnitType: 17},
      },
      HoursOfSun: 10.7,
      DegreeDaySummary: {
        Heating: {Value: 0.0, Unit: 'C', UnitType: 17},
        Cooling: {Value: 1.0, Unit: 'C', UnitType: 17},
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {Name: 'Grass', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Mold', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Ragweed', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Tree', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'UVIndex', Value: 4, Category: 'Moderate', CategoryValue: 2},
      ],
      Day: {
        Icon: 1,
        IconPhrase: 'Sunny',
        HasPrecipitation: false,
        ShortPhrase: 'Sunny and delightful',
        LongPhrase: 'Delightful with plenty of sunshine',
        PrecipitationProbability: 0,
        ThunderstormProbability: 0,
        RainProbability: 0,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 9.3, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 323, Localized: 'NW', English: 'NW'},
        },
        WindGust: {
          Speed: {Value: 13.0, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 320, Localized: 'NW', English: 'NW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 0,
      },
      Night: {
        Icon: 33,
        IconPhrase: 'Clear',
        HasPrecipitation: false,
        ShortPhrase: 'Clear',
        LongPhrase: 'Clear',
        PrecipitationProbability: 0,
        ThunderstormProbability: 0,
        RainProbability: 0,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 9.3, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 317, Localized: 'NW', English: 'NW'},
        },
        WindGust: {
          Speed: {Value: 13.0, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 316, Localized: 'NW', English: 'NW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 0,
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://m.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=3&unit=c&lang=en-us',
      Link:
        'http://www.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=3&unit=c&lang=en-us',
    },
    {
      Date: '2019-12-19T07:00:00+06:00',
      EpochDate: 1576717200,
      Sun: {
        Rise: '2019-12-19T06:35:00+06:00',
        EpochRise: 1576715700,
        Set: '2019-12-19T17:16:00+06:00',
        EpochSet: 1576754160,
      },
      Moon: {
        Rise: null,
        EpochRise: null,
        Set: '2019-12-19T12:17:00+06:00',
        EpochSet: 1576736220,
        Phase: 'Last',
        Age: 23,
      },
      Temperature: {
        Minimum: {Value: 12.6, Unit: 'C', UnitType: 17},
        Maximum: {Value: 25.0, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperature: {
        Minimum: {Value: 12.3, Unit: 'C', UnitType: 17},
        Maximum: {Value: 26.0, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperatureShade: {
        Minimum: {Value: 12.3, Unit: 'C', UnitType: 17},
        Maximum: {Value: 23.7, Unit: 'C', UnitType: 17},
      },
      HoursOfSun: 7.6,
      DegreeDaySummary: {
        Heating: {Value: 0.0, Unit: 'C', UnitType: 17},
        Cooling: {Value: 1.0, Unit: 'C', UnitType: 17},
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {Name: 'Grass', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Mold', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Ragweed', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Tree', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'UVIndex', Value: 4, Category: 'Moderate', CategoryValue: 2},
      ],
      Day: {
        Icon: 5,
        IconPhrase: 'Hazy sunshine',
        HasPrecipitation: false,
        ShortPhrase: 'Hazy sun',
        LongPhrase: 'Hazy sun',
        PrecipitationProbability: 0,
        ThunderstormProbability: 0,
        RainProbability: 0,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 9.3, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 303, Localized: 'WNW', English: 'WNW'},
        },
        WindGust: {
          Speed: {Value: 14.8, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 291, Localized: 'WNW', English: 'WNW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 31,
      },
      Night: {
        Icon: 37,
        IconPhrase: 'Hazy moonlight',
        HasPrecipitation: false,
        ShortPhrase: 'Hazy',
        LongPhrase: 'Hazy',
        PrecipitationProbability: 0,
        ThunderstormProbability: 0,
        RainProbability: 0,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 7.4, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 311, Localized: 'NW', English: 'NW'},
        },
        WindGust: {
          Speed: {Value: 11.1, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 325, Localized: 'NW', English: 'NW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 31,
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://m.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=4&unit=c&lang=en-us',
      Link:
        'http://www.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=4&unit=c&lang=en-us',
    },
    {
      Date: '2019-12-20T07:00:00+06:00',
      EpochDate: 1576803600,
      Sun: {
        Rise: '2019-12-20T06:35:00+06:00',
        EpochRise: 1576802100,
        Set: '2019-12-20T17:16:00+06:00',
        EpochSet: 1576840560,
      },
      Moon: {
        Rise: '2019-12-20T00:28:00+06:00',
        EpochRise: 1576780080,
        Set: '2019-12-20T12:57:00+06:00',
        EpochSet: 1576825020,
        Phase: 'WaningCrescent',
        Age: 24,
      },
      Temperature: {
        Minimum: {Value: 12.5, Unit: 'C', UnitType: 17},
        Maximum: {Value: 24.8, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperature: {
        Minimum: {Value: 12.4, Unit: 'C', UnitType: 17},
        Maximum: {Value: 26.0, Unit: 'C', UnitType: 17},
      },
      RealFeelTemperatureShade: {
        Minimum: {Value: 12.4, Unit: 'C', UnitType: 17},
        Maximum: {Value: 23.5, Unit: 'C', UnitType: 17},
      },
      HoursOfSun: 6.6,
      DegreeDaySummary: {
        Heating: {Value: 0.0, Unit: 'C', UnitType: 17},
        Cooling: {Value: 1.0, Unit: 'C', UnitType: 17},
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {Name: 'Grass', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Mold', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Ragweed', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'Tree', Value: 0, Category: 'Low', CategoryValue: 1},
        {Name: 'UVIndex', Value: 4, Category: 'Moderate', CategoryValue: 2},
      ],
      Day: {
        Icon: 5,
        IconPhrase: 'Hazy sunshine',
        HasPrecipitation: false,
        ShortPhrase: 'Hazy sun',
        LongPhrase: 'Hazy sun',
        PrecipitationProbability: 0,
        ThunderstormProbability: 0,
        RainProbability: 0,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 9.3, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 316, Localized: 'NW', English: 'NW'},
        },
        WindGust: {
          Speed: {Value: 13.0, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 298, Localized: 'WNW', English: 'WNW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 38,
      },
      Night: {
        Icon: 37,
        IconPhrase: 'Hazy moonlight',
        HasPrecipitation: false,
        ShortPhrase: 'Hazy',
        LongPhrase: 'Hazy',
        PrecipitationProbability: 0,
        ThunderstormProbability: 0,
        RainProbability: 0,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {Value: 7.4, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 331, Localized: 'NNW', English: 'NNW'},
        },
        WindGust: {
          Speed: {Value: 11.1, Unit: 'km/h', UnitType: 7},
          Direction: {Degrees: 295, Localized: 'WNW', English: 'WNW'},
        },
        TotalLiquid: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Rain: {Value: 0.0, Unit: 'mm', UnitType: 3},
        Snow: {Value: 0.0, Unit: 'cm', UnitType: 4},
        Ice: {Value: 0.0, Unit: 'mm', UnitType: 3},
        HoursOfPrecipitation: 0.0,
        HoursOfRain: 0.0,
        HoursOfSnow: 0.0,
        HoursOfIce: 0.0,
        CloudCover: 34,
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://m.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=5&unit=c&lang=en-us',
      Link:
        'http://www.accuweather.com/en/bd/dhaka/28143/daily-weather-forecast/28143?day=5&unit=c&lang=en-us',
    },
  ],
};

export default array;
